### ISSUE TITLE
Commands cannot be enabled in 1.8

### ISSUE THREAD

**Issue by erikzimmermann** [erikzimmermann/WarpSystem-Code#437]
java.lang.NoSuchMethodError: org.bukkit.command.PluginCommand.setName(Ljava/lang/String;)Z
at de.codingair.codingapi.server.commands.CommandBuilder.register(CommandBuilder.java:72)
at de.codingair.warpsystem.spigot.features.warps.managers.IconManager.load(IconManager.java:215)
at de.codingair.warpsystem.spigot.base.managers.DataManager.load(DataManager.java:32)
at de.codingair.warpsystem.spigot.base.WarpSystem.onEnable(WarpSystem.java:139)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
at java.lang.Thread.run(Unknown Source)

**Comment by erikzimmermann** [comment]
Fixed with new API.
